POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Benny Smith",
    "number": "25-63-4236"
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Arto Hellas"
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "number": "040-123456"
}